version: 2.1
orbs:
  cypress: cypress-io/cypress@1.27.0
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          yarn: true
          install-command: yarn install --frozen-lockfile
          executor: cypress/base-14
          start: npm start
          wait-on: "http://localhost:3000"
